// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWINtEoM6zjhncYeu_aGxGnbArFt0WZZk',
    appId: '1:184050155801:web:f4bfdb1c8374db126e4588',
    messagingSenderId: '184050155801',
    projectId: 'u22procon-bc3be',
    authDomain: 'u22procon-bc3be.firebaseapp.com',
    storageBucket: 'u22procon-bc3be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcWO1LePEa6rkghCe4Q9bbuBLVNssB_9g',
    appId: '1:184050155801:android:94289f8834387ef16e4588',
    messagingSenderId: '184050155801',
    projectId: 'u22procon-bc3be',
    storageBucket: 'u22procon-bc3be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJSecfGVNnMg6RzhJTvmhAWl76QkBAoxs',
    appId: '1:184050155801:ios:20d82c10d7d042996e4588',
    messagingSenderId: '184050155801',
    projectId: 'u22procon-bc3be',
    storageBucket: 'u22procon-bc3be.appspot.com',
    iosClientId: '184050155801-gda464ghn718da7ubu3u6tjp8ccsqcj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.u22Procon',
  );

}